### ISSUE TITLE
接入指南-步骤3复制 Worker 源码失败

### ISSUE THREAD

**Issue by raotaohub** [AlloyTeam/alloy-worker#5]
1. 下载源码 : 下载 template demo 项目 ; 顺利
2.  安装 alloy-worker: cd template && 安装 alloy-worker ：顺利
3.  复制 Worker 源码 ： 失败
`$ npx alloy-worker eject
The syntax of the command is incorrect.
child_process.js:866
    throw err;
    ^

Error: Command failed: mkdir -p src/
The syntax of the command is incorrect.

    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at module.exports (D:\rt\reacat-wp5\node_modules\alloy-worker\src\command\eject-script.js:15:5)
    at Object.<anonymous> (D:\rt\reacat-wp5\node_modules\alloy-worker\src\command\index.js:27:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(41) [Uint8Array] [
       84, 104, 101,  32, 115, 121, 110, 116,  97,
      120,  32, 111, 102,  32, 116, 104, 101,  32,
       99, 111, 109, 109,  97, 110, 100,  32, 105,
      115,  32, 105, 110,  99, 111, 114, 114, 101,
       99, 116,  46,  13,  10
    ]
  ],
  pid: 22176,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(41) [Uint8Array] [
     84, 104, 101,  32, 115, 121, 110, 116,  97,
    120,  32, 111, 102,  32, 116, 104, 101,  32,
     99, 111, 109, 109,  97, 110, 100,  32, 105,
    115,  32, 105, 110,  99, 111, 114, 114, 101,
     99, 116,  46,  13,  10
  ]
}
`
`
'pwd' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
child_process.js:866
    throw err;
    ^

Error: Command failed: pwd
'pwd' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at Object.<anonymous> (D:\rt\reacat-wp5\node_modules\alloy-worker\src\command\one-script\config.js:13:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (D:\rt\reacat-wp5\node_modules\alloy-worker\src\command\one-script\check-name.js:6:16) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(62) [Uint8Array] [
       39, 112, 119, 100,  39,  32, 178, 187, 202, 199,
      196, 218, 178, 191, 187, 242, 205, 226, 178, 191,
      195, 252, 193, 238, 163, 172, 210, 178, 178, 187,
      202, 199, 191, 201, 212, 203, 208, 208, 181, 196,
      179, 204, 208, 242,  13,  10, 187, 242, 197, 250,
      180, 166, 192, 237, 206, 196, 188, 254, 161, 163,
       13,  10
    ]
  ],
  pid: 26848,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(62) [Uint8Array] [
     39, 112, 119, 100,  39,  32, 178, 187, 202, 199,
    196, 218, 178, 191, 187, 242, 205, 226, 178, 191,
    195, 252, 193, 238, 163, 172, 210, 178, 178, 187,
    202, 199, 191, 201, 212, 203, 208, 208, 181, 196,
    179, 204, 208, 242,  13,  10, 187, 242, 197, 250,
    180, 166, 192, 237, 206, 196, 188, 254, 161, 163,
     13,  10
  ]
}
`

我是在template的与src同级的目录下执行 npx alloy-worker eject 命令
node-v : 14.18.0

**Comment by raotaohub** [comment]
我手动复制进去解决了
